// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yaghane360.Data.Kullanici;

#nullable disable

namespace Yaghane360.Migrations.ZeytinTakipDB
{
    [DbContext(typeof(ZeytinTakipDBContext))]
    partial class ZeytinTakipDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Box", b =>
                {
                    b.Property<int>("BoxID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoxID"));

                    b.Property<decimal?>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MusteriID")
                        .HasColumnType("int");

                    b.HasKey("BoxID");

                    b.HasIndex("MusteriID");

                    b.ToTable("Boxlar");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Kasa", b =>
                {
                    b.Property<int>("KasaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasaID"));

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KasaID");

                    b.ToTable("Kasalar");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.KasaGider", b =>
                {
                    b.Property<int>("KasaGiderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasaGiderID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiderTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslemiYapanKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KasaID")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MusteriID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KasaGiderID");

                    b.HasIndex("KasaID");

                    b.HasIndex("MusteriID");

                    b.ToTable("KasaGider");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.KasaIslemleri", b =>
                {
                    b.Property<int>("KasaIslemNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasaIslemNo"));

                    b.Property<string>("IslemiYapanKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KasaID")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KasaIslemNo");

                    b.HasIndex("KasaID");

                    b.HasIndex("MusteriID");

                    b.ToTable("KasaIslemleri");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Machine", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineID"));

                    b.Property<int?>("IslemNo")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ZamanSayaci")
                        .HasColumnType("time");

                    b.HasKey("MachineID");

                    b.HasIndex("IslemNo");

                    b.ToTable("Makineler");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Musteri", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Borc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StokYag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StokZeytin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YagHacim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ZeytinHacim")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Urun", b =>
                {
                    b.Property<int>("IslemNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemNo"));

                    b.Property<int?>("BoxID")
                        .HasColumnType("int");

                    b.Property<bool?>("IslemDurum")
                        .HasColumnType("bit");

                    b.Property<int?>("MusteriID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TarihCikti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TarihGirdi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("YagKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ZeytinKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IslemNo");

                    b.HasIndex("BoxID");

                    b.HasIndex("MusteriID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Box", b =>
                {
                    b.HasOne("Yaghane360.Data.Kullanici.Musteri", "Musteri")
                        .WithMany("Boxlar")
                        .HasForeignKey("MusteriID");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.KasaGider", b =>
                {
                    b.HasOne("Yaghane360.Data.Kullanici.Kasa", "Kasa")
                        .WithMany()
                        .HasForeignKey("KasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yaghane360.Data.Kullanici.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriID");

                    b.Navigation("Kasa");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.KasaIslemleri", b =>
                {
                    b.HasOne("Yaghane360.Data.Kullanici.Kasa", "Kasa")
                        .WithMany("Islemler")
                        .HasForeignKey("KasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yaghane360.Data.Kullanici.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasa");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Machine", b =>
                {
                    b.HasOne("Yaghane360.Data.Kullanici.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("IslemNo");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Urun", b =>
                {
                    b.HasOne("Yaghane360.Data.Kullanici.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxID");

                    b.HasOne("Yaghane360.Data.Kullanici.Musteri", "Musteri")
                        .WithMany("Urunler")
                        .HasForeignKey("MusteriID");

                    b.Navigation("Box");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Kasa", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("Yaghane360.Data.Kullanici.Musteri", b =>
                {
                    b.Navigation("Boxlar");

                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
